version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - misspell
    - noctx
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - gosec

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    revive:
      rules:
        - name: exported
          disabled: false
    gosec:
      excludes: []

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
